In [ ]:
#Bai 1: Doc file bien_xe.txt, nhap cac bien so cach nhau boi dau phay

In [16]:
# Đọc dữ liệu từ file
ma_tinh = {}
with open("bien_so_xe.txt", "r") as f:
    for line in f:
        if ':' in line:
            phan = line.strip().split(':')
            ten = phan[0]
            ma = phan[1]
            ma_tinh[ma] = ten

In [21]:
bien_so = input("Nhập biển số xe: ")
ds = bien_so.split(',')

Nhập biển số xe:  38AK-04700,20AE-000


In [22]:
for bien_so in ds:
    bien_so = bien_so.strip()  
    ma = bien_so[:2]
    if ma in ma_tinh:
        ten = ma_tinh[ma]
    else:
        ten = "Không rõ"
    print(ten)

Ha Tinh
Thai Nguyen


In [23]:
import numpy as np

In [25]:
#Tạo ma trận A
A = np.array([[1,-5,2],[-3,1,0],[4,3,-2]])
A

array([[ 1, -5,  2],
       [-3,  1,  0],
       [ 4,  3, -2]])

In [26]:
#Tạo ma trận B
B = np.array([[-3,4,1],[-1,5,-2],[0,1,6]])
B

array([[-3,  4,  1],
       [-1,  5, -2],
       [ 0,  1,  6]])

In [48]:
C = A@B - B@A + 4*A**2 - 9*B**2

In [49]:
C

array([[ -64,  -85,   38],
       [  59, -232,  -43],
       [  28,   37, -310]])

In [50]:
I = np.identity(3)

In [55]:
D = np.block([[I,-A,B],[-A,A@A,-A@B]])

In [56]:
D

array([[  1.,   0.,   0.,  -1.,   5.,  -2.,  -3.,   4.,   1.],
       [  0.,   1.,   0.,   3.,  -1.,   0.,  -1.,   5.,  -2.],
       [  0.,   0.,   1.,  -4.,  -3.,   2.,   0.,   1.,   6.],
       [ -1.,   5.,  -2.,  24.,  -4.,  -2.,  -2.,  19., -23.],
       [  3.,  -1.,   0.,  -6.,  16.,  -6.,  -8.,   7.,   5.],
       [ -4.,  -3.,   2., -13., -23.,  12.,  15., -29.,  14.]])

In [57]:
r_D = np.linalg.matrix_rank(D)

In [58]:
r_D

3

In [59]:
np.linalg.solve(A,B[:,0])

array([ 5., 14., 31.])

In [60]:
import pandas as pd

In [61]:
f = pd.read_csv("absent_employees.csv")

In [62]:
f

EmployeeNumber    Surname GivenName Gender             City  \
0                  1  Gutierrez     Molly      F          Burnaby   
1                  2   Hardwick   Stephen      M        Courtenay   
2                  3    Delgado   Chester      M         Richmond   
3                  4      Simon     Irene      F         Victoria   
4                  5   Delvalle    Edward      M  New Westminster   
...              ...        ...       ...    ...              ...   
8331            8332   Coniglio    Bianca      F          Langley   
8332            8333        Cox    Jimmie      M          Montney   
8333            8334    Hawkins      Mary      F   West Vancouver   
8334            8335    Proctor   Theresa      F        Vancouver   
8335            8336     Salter   Charles      M        Vancouver   

          JobTitle    DepartmentName    StoreLocation Division        Age  \
0            Baker            Bakery          Burnaby   Stores  32.028816   
1            Baker            Bakery          Nanaimo   Stores  40.320902   
2            Baker            Bakery         Richmond   Stores  48.822047   
3            Baker            Bakery         Victoria   Stores  44.599357   
4            Baker            Bakery  New Westminster   Stores  35.697876   
...            ...               ...              ...      ...        ...   
8331       Cashier  Customer Service          Langley   Stores  46.057544   
8332       Cashier  Customer Service     Fort St John   Stores  34.455490   
8333       Cashier  Customer Service   West Vancouver   Stores  58.347160   
8334  Dairy Person             Dairy        Vancouver   Stores  43.340616   
8335  Dairy Person             Dairy        Vancouver   Stores  46.192782   

      LengthService  AbsentHours BusinessUnit  
0          6.018478    36.577306       Stores  
1          5.532445    30.165072       Stores  
2          4.389973    83.807798       Stores  
3          3.081736    70.020165       Stores  
4          3.619091     0.000000       Stores  
...             ...          ...          ...  
8331       4.838288    93.665111       Stores  
8332       2.427274     0.000000       Stores  
8333       4.009393   176.356940       Stores  
8334       6.154837    60.321917       Stores  
8335       5.174722   112.023389       Stores  

[8336 rows x 13 columns]

In [46]:
f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8336 entries, 0 to 8335
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   EmployeeNumber  8336 non-null   int64  
 1   Surname         8336 non-null   object 
 2   GivenName       8336 non-null   object 
 3   Gender          8336 non-null   object 
 4   City            8336 non-null   object 
 5   JobTitle        8336 non-null   object 
 6   DepartmentName  8336 non-null   object 
 7   StoreLocation   8336 non-null   object 
 8   Division        8336 non-null   object 
 9   Age             8336 non-null   float64
 10  LengthService   8336 non-null   float64
 11  AbsentHours     8336 non-null   float64
 12  BusinessUnit    8336 non-null   object 
dtypes: float64(3), int64(1), object(9)
memory usage: 846.8+ KB


In [47]:
f.isna().sum()

EmployeeNumber    0
Surname           0
GivenName         0
Gender            0
City              0
JobTitle          0
DepartmentName    0
StoreLocation     0
Division          0
Age               0
LengthService     0
AbsentHours       0
BusinessUnit      0
dtype: int64